-- Include your INSERT SQL statements in this file.
-- Make sure to terminate each statement with a semicolon (;)

-- LEAVE this statement on. It is required to connect to your database.
CONNECT TO COMP421;

-- Remember to put the INSERT statements for the tables with foreign key references
--    ONLY AFTER the insert for the parent tables!

-- This is only an example of how you add INSERT statements to this file.
--   You may remove it.


-- Artists
INSERT INTO Artists (artist_id, name, birth) VALUES (1, 'Anonymous', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (2, 'Michelangelo', '1475-03-06');
INSERT INTO Artists (artist_id, name, birth) VALUES (3, 'Antonio Canova', '1757-11-01');
INSERT INTO Artists (artist_id, name, birth) VALUES (4, 'Alexandros of Antioch', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (5, 'Gian Lorenzo Bernini', '1598-12-07');
INSERT INTO Artists (artist_id, name, birth) VALUES (6, 'Agasias', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (7, 'Antoine Coysevox', '1640-09-29');
INSERT INTO Artists (artist_id, name, birth) VALUES (8, 'Guillaume Coustou', '1677-11-29');
INSERT INTO Artists (artist_id, name, birth) VALUES (9, 'Leonardo da Vinci', '1452-04-15');
INSERT INTO Artists (artist_id, name, birth) VALUES (10, 'Theodore Gericault', '1791-09-26');
INSERT INTO Artists (artist_id, name, birth) VALUES (11, 'Sandro Botticelli', '1445-03-01');
INSERT INTO Artists (artist_id, name, birth) VALUES (12, 'Johannes Vermeer', '1632-10-31');
INSERT INTO Artists (artist_id, name, birth) VALUES (13, 'Jean-Auguste-Dominique Ingres', '1780-08-29');
INSERT INTO Artists (artist_id, name, birth) VALUES (14, 'Paolo Veronese', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (15, 'Eugene Delacroix', '1798-04-26');
INSERT INTO Artists (artist_id, name, birth) VALUES (16, 'Jacques-Louis David', '1748-08-30');
INSERT INTO Artists (artist_id, name, birth) VALUES (17, 'Caravaggio', '1571-09-29');
INSERT INTO Artists (artist_id, name, birth) VALUES (18, 'Jean-Antoine Watteau', '1684-10-10');
INSERT INTO Artists (artist_id, name, birth) VALUES (19, 'Jean-Baptiste-Simeon Chardin', '1699-11-02');
INSERT INTO Artists (artist_id, name, birth) VALUES (20, 'Diego Velazquez', '1599-06-06');
INSERT INTO Artists (artist_id, name, birth) VALUES (21, 'Nicolaes Maes', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (22, 'Rembrandt', '1606-07-15');
INSERT INTO Artists (artist_id, name, birth) VALUES (23, 'Antoine-Louis Barye', '1796-09-24');
INSERT INTO Artists (artist_id, name, birth) VALUES (24, 'Pierre Puget', '1620-10-16');
INSERT INTO Artists (artist_id, name, birth) VALUES (25, 'Jean-Baptiste Pigalle', '1714-02-27');
INSERT INTO Artists (artist_id, name, birth) VALUES (26, 'Laurent Ronde', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (27, 'Evrard Bapst', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (28, 'Frederic Bapst', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (29, 'Alexandre-Gabriel Lemonnier', '1808-05-14');
INSERT INTO Artists (artist_id, name, birth) VALUES (30, 'Gyokuyo-sai', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (31, 'Tomochika Chikuyo-sai', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (32, 'Martin-Guillaume Biennais', '1764-04-29');
INSERT INTO Artists (artist_id, name, birth) VALUES (33, 'Giulio Romano', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (34, 'Bernard van Orley', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (35, 'Martin van den Bogaert', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (36, 'Shoun-sai', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (37, 'Hakuun-sai', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (38, 'Edgar Degas', '1834-07-19');
INSERT INTO Artists (artist_id, name, birth) VALUES (39, 'Joseph Kosuth', '1945-01-31');
INSERT INTO Artists (artist_id, name, birth) VALUES (40, 'Julien Le Roy', '1686-08-06');
INSERT INTO Artists (artist_id, name, birth) VALUES (41, 'Amy Huaud', '1657-08-09');
INSERT INTO Artists (artist_id, name, birth) VALUES (42, 'Jean-Pierre Huaud', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (43, 'Alexandre-Louis Bellange', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (44, 'Jean Jacques Feuchere', '1807-08-24');
INSERT INTO Artists (artist_id, name, birth) VALUES (45, 'Jerome-Martin Langlois', '1779-03-11');
INSERT INTO Artists (artist_id, name, birth) VALUES (46, 'Alexandre Roslin', '1718-07-15');
INSERT INTO Artists (artist_id, name, birth) VALUES (47, 'Jan de Bray', NULL);
INSERT INTO Artists (artist_id, name, birth) VALUES (48, 'Gustave Adolphe Chassevent', '1818-02-05');
INSERT INTO Artists (artist_id, name, birth) VALUES (49, 'Franz Xaver Winterhalter', '1805-04-20');
INSERT INTO Artists (artist_id, name, birth) VALUES (50, 'Pierre-Jean David d�Angers', '1788-03-12');

-- Genres
INSERT INTO Genres (genre_name) VALUES ('Abstract');
INSERT INTO Genres (genre_name) VALUES ('Renaissance');
INSERT INTO Genres (genre_name) VALUES ('Neoclassic');
INSERT INTO Genres (genre_name) VALUES ('Romanticism');
INSERT INTO Genres (genre_name) VALUES ('Contemporary');
INSERT INTO Genres (genre_name) VALUES ('Baroque');
INSERT INTO Genres (genre_name) VALUES ('Realism');
INSERT INTO Genres (genre_name) VALUES ('Impressionism');
INSERT INTO Genres (genre_name) VALUES ('Hellenistic');
INSERT INTO Genres (genre_name) VALUES ('Religious');
INSERT INTO Genres (genre_name) VALUES ('Mannerism');
INSERT INTO Genres (genre_name) VALUES ('Rococo');
INSERT INTO Genres (genre_name) VALUES ('Japanese Edo-period');
INSERT INTO Genres (genre_name) VALUES ('Gothic');
INSERT INTO Genres (genre_name) VALUES ('Armory');
INSERT INTO Genres (genre_name) VALUES ('Clothing');
INSERT INTO Genres (genre_name) VALUES ('Decorative art');
INSERT INTO Genres (genre_name) VALUES ('Jewels');
INSERT INTO Genres (genre_name) VALUES ('Coins and medals');
INSERT INTO Genres (genre_name) VALUES ('Egyptian');
INSERT INTO Genres (genre_name) VALUES ('Sumerian');

-- Visitor
INSERT INTO Visitor (email, name, address, birth) VALUES ('cnani0@studiopress.com', 'Cory', 'Apt 359', '1999-06-19');
INSERT INTO Visitor (email, name, address, birth) VALUES ('afrays1@elegantthemes.com', 'April', '15th Floor', '2000-03-27');
INSERT INTO Visitor (email, name, address, birth) VALUES ('nathan222@shinystat.com', 'Nathan', 'PO Box 10414', '2001-10-09');
INSERT INTO Visitor (email, name, address, birth) VALUES ('mdurdan3@bigcartel.com', 'Melissa', 'Apt 703', '2009-04-20');
INSERT INTO Visitor (email, name, address, birth) VALUES ('rclulee4@alibaba.com', 'Reagen', 'Suite 59', '1987-01-14');
INSERT INTO Visitor (email, name, address, birth) VALUES ('natwood4@cnet.com', 'Natasha', 'Room 167', '2006-09-09');
INSERT INTO Visitor (email, name, address, birth) VALUES ('zach4000@yahoo.com', 'Zachary', 'Suite 59', '1985-04-27');
INSERT INTO Visitor (email, name, address, birth) VALUES ('slaviste9@nhs.uk', 'Sileas', '2nd Floor', '1998-03-20');
INSERT INTO Visitor (email, name, address, birth) VALUES ('cguppya@google.nl', 'Craig', '10th Floor', '1998-10-01');
INSERT INTO Visitor (email, name, address, birth) VALUES ('lrumbleb@weebly.com', 'Lani', '15th Floor', '2006-01-15');
INSERT INTO Visitor (email, name, address, birth) VALUES ('ewhichelowc@biglobe.ne.jp', 'Elwin', 'Suite 36', '1995-01-12');
INSERT INTO Visitor (email, name, address, birth) VALUES ('cioselevichd@networksolutions.com', 'Conant', 'Room 536', '1987-06-15');
INSERT INTO Visitor (email, name, address, birth) VALUES ('ggainforthe@ox.ac.uk', 'Griffin', '6th Floor', '2003-10-28');
INSERT INTO Visitor (email, name, address, birth) VALUES ('mrelf2@newsvine.com', 'Mathilde', 'Suite 8', '1979-05-11');
INSERT INTO Visitor (email, name, address, birth) VALUES ('abroosea@chronoengine.com', 'Andree', 'Room 282', '2010-01-09');
INSERT INTO Visitor (email, name, address, birth) VALUES ('sdunsb@quantcast.com', 'Sloan', 'Suite 21', '1992-09-02');
INSERT INTO Visitor (email, name, address, birth) VALUES ('lgraystonc@gravatar.com', 'Liva', 'PO Box 90552', '2001-07-26');
INSERT INTO Visitor (email, name, address, birth) VALUES ('sferrullid@sogou.com', 'Simmonds', 'Suite 38', '1984-07-15');
INSERT INTO Visitor (email, name, address, birth) VALUES ('jsaintepaule@privacy.gov.au', 'Jules', 'PO Box 5572', '1999-10-01');
INSERT INTO Visitor (email, name, address, birth) VALUES ('mmorais0@nationalgeographic.com', 'Maurise', 'Suite 36', '2008-12-19');

-- Museum_Personnel
INSERT INTO Museum_Personnel (employee_id, name) VALUES (1, 'Christopher');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (2, 'Brynne');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (3, 'Reuben');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (4, 'Tara');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (5, 'Hayden');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (6, 'Bob');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (7, 'Guillaume');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (8, 'William');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (9, 'Jenna');
INSERT INTO Museum_Personnel (employee_id, name) VALUES (10, 'Andy');

-- Artifacts
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (1, 'The Winged Victory of Samothrace', 'It is a masterpiece of Hellenistic Greek sculpture that depicts Nike, the Greek goddess of victory, descending onto the prow of a ship. The sculpture shows the goddess with large outstretched wings and was created at around 190 BC.', -190);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (2, 'The Dying Slave', 'The piece is an unfinished sculpture, featuring a young, nude male figure in a contrapposto pose. He is shown in a deep, perhaps eternal sleep, with his head tilted back, one arm bent behind his head, and the other resting on his chest. The statue was commissioned by Pope Julius II as part of a decorative  funerary monument, but the project was abandone, leaving the sculptures incomplete and symbolically imprisoned within the marble.', 1513);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (3, 'The Rebellious Slave', 'The Rebellious Slave portrays a straining, nude male figure with hands tied behind his back, twisting in a violent struggle to break free. One arm is raised behind his head while the other presses against his torso, enhancing the sense of struggle and confinement. Like the Dying Slave, the Rebellious Slave was commissioned by Pope Julius II for a grand funerary monument, but the project was abandoned, leaving the figure unfinished.', 1513);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (4, 'Psyche Revived by Cupid''s Kiss', 'It depicts the climax of the myth from Apuleius''s The Golden Ass, where Cupid gently awakens the lifeless Psyche with a tender kiss after she falls into a deep, forbidden slumber. Cupid is shown kneeling, cradling the head and breast of a reclining, swooning Psyche, who raises her arms to embrace him. The piece captures the moment between absolute stillness and returning life.', 1793);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (5, 'Venus de Milo', 'The Venus de Milo is a famous Ancient Greek sculpture, created around 100 BC, likely  representing the goddess Aphrodite. The partially nude statue is depicted with a bare torso and drapery over the lower half of her body. Both arms, the left foot, and the earlobes are missing. It is celebrated for its graceful, draped form, S-curve pose, and serene expression.', -100);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (6, 'Sleeping Hermaphroditus', 'The statue is an ancient Roman sculpture depicting Hermaphroditus, the mythological child of Hermes and Aphrodite. The figure lies on its stomach in a pose of intimate repose, surprising viewers with a dual-gendered form: a feminine back and hips combined with male genitalia.', 1620);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (7, 'Borghese Gladiator', 'It depicts a life-size, nude warrior in a dynamic, forward-lunging posture, originally thought to be a gladiator but likely representing a fighter defending against a mounted combatant. The figure is intensely athletic, with his weight on his right leg, body leaning forward, left arm outstretched (originally holding a shield), and right arm lowered. It represents a moment of intense battle action.', -100);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (8, 'Fame Riding Pegasus', 'The Fame Riding Pegasus is a Baroque-style sculpture representing that depicts the Renommee (the Fame of King Louis XIV) blowing a trumpet while riding the winged horse Pegasus. It symbolizes the "Sun King" Louis XIV''s military victories, prestige, and immortality.', 1701);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (9, 'The Marly Horses', 'The sculpture depicts earing, untamed horses being restrained by muscular grooms. It was commissioned by  King Louis XV for the Chateau de Marly, they are renowned for their intense realism, dynamic movement, and lack of mythological allegory.', 1743);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (10, 'Ceres', 'The statue depicts Ceres, the Roman goddess of agriculture,fertility, and summer. Standing over three meters tall, the figure is richly detailed in cascading drapery and classical form, reflecting the influence of antiquity on 18th?century French sculpture.', 1731);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (11, 'The Mona Lisa', 'The Mona Lisa is a portrait of a seated woman, widely recognized for her enigmatic smile and calm, poised demeanor. Leonardo da Vinci employs sfumato, a technique of soft, gradual shading, to create lifelike transitions between light and shadow, giving her face a subtle, almost three-dimensional quality. The figure is set against a distant, atmospheric landscape, enhancing the sense of depth and perspective.', 1503);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (12, 'The Raft of the Medusa', 'The Raft of the Medusa is a monumental Romantic painting depicting the aftermath of a French shipwreck where 150 people were abandoned on a makeshift raft, leaving only 15 survivors after 13 days of starvation, cannibalism, and brutality. It captures the dramatic moment they spot the rescue ship, Argus.', 1819);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (13, 'The Virgin and Child with Saint Anne', 'It depicts St. Anne, her daughter the Virgin Mary, and the infant Jesus interacting with a lamb, symbolizing his future sacrifice. The composition is noted for its pyramidal structure, soft sfumato technique, and emotional intimacy.', 1501);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (14, 'Saint John the Baptist', 'The painting is renowned for its extreme sfumato and chiaroscuro, portraying an androgynous, youthful John with an enigmatic smile, emerging from profound darkness. he figure has long, curly hair, soft features, and is dressed in animal skins. The saint leans forward, holding a reed cross in his left hand, while his right hand points upward toward heaven, a gesture that symbolizes the spiritual dimension of salvation.', 1513);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (15, 'La Belle Ferronniere', 'La Belle Ferronniere is a renowed portrait  or his Milanese studio, housed in the Louvre Museum. The masterpiece featuring a half-length, three-quarter view of an unknown, noblewoman with a direct yet intense gaze, wearing a dark red dress and a characteristic, jeweled headband. The painting exhibits Leonardo''s signature sfumato technique and a profound, psychologically intense expression.', 1490);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (16, 'Venus and the Three Graces Presenting Gifts to a Young Woman', 'The painting depicts mythological figures offering roses to a young woman, likely Giovanna Tornabuoni for her wedding. It is an allegory celebrating an engagement, focusing on the act of giving. Venus, the goddess of love, presents roses to a young woman, while the Three Graces, representing beauty, charm, and joy, accompany her.', 1486);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (17, 'The Lacemaker', 'The Lacemaker is a small, intimate painting depicting a young Dutch woman, dressed in a yellow bodice with a white collar, intensely focused on crafting lace. It highlights domestic virtue, using warm tones on the subject against a cool background to emphasize her concentration and the delicate, precise handiwork.', 1670);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (18, 'La Grande Odalisque', 'The painting  depicts a reclining nude woman, or odalisque, surrounded by luxurious Orientalist fabrics. Her back is turned to the viewer, but she turns her head to look directly forward, creating a gaze that is both melancholic and inviting.', 1814);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (19, 'The Wedding at Cana', 'The piece shows Christ''s first miracle. Jesus and Mary are positioned at the center of a lavish U-shaped table, emphasizing their significance, with Jesus performing the miracle of turning water into wine. The scene serves as a display of Venetian wealth and power.', 1563);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (20, 'Liberty Leading the People', 'It depicts a bare-breasted allegorical figure of Liberty (Marianne) brandishing the French tricolor flag and a musket, leading a diverse group of revolutionaries over barricades and fallen bodies. The painting represents the Three Glorious Days of the 1830 revolution against King Charles X. It highlights unity between the working and middle classes.', 1830);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (21, 'The Astronomer', 'The piece depicts a scholar in a sunlit, scholarly, 17th-century Dutch study. The man, possibly scientist Antonie van Leeuwenhoek, is focused on a celestial globe, surrounded by tools symbolizing knowledge, including a book by Metius and a painting of Moses.', 1668);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (22, 'The Coronation of Napoleon', 'The Coronation of Napoleon depicts Napoleon I crowning Empress Josephine at Notre-Dame on December 2, 1804. The masterpiece highlights imperial power, featuring precise, dramatic lighting, and a cast of over 100 figures, including a seated Pope Pius VII.', 1807);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (23, 'Oath of the Horatii', 'It depicts three Roman brothers swearing to fight to the death against the Curiatii of Alba Longa to defend their city. The painting emphasizes civic duty, patriotism, and masculine sacrifice, contrasting rigid, heroic male figures with emotional, passive women.', 1784);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (24, 'Death of the Virgin', 'The piece famously depicts the Virgin Mary as a bloated, ordinary corpse, likely modeled after a drowned prostitute. Contrary to tradition, Mary is not shown rising to heaven, but as a dead body with a swollen abdomen, a limp arm, and a pale complexion. The scene portrays the Dormition (falling asleep) of the Virgin, yet presents it as a common, tragic death. The only nod to divinity is a faint, thin halo.', 1606);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (25, 'The Intervention of the Sabine Women', 'The painting depicts the aftermath of the Sabine women''s abduction. It shows Hersilia, wife of Romulus, rushing between her husband and her father to stop the bloodshed. The masterpiece, created during the French Revolution, symbolizes peace, reconciliation, and love overcoming conflict.', 1799);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (26, 'Portrait of Madame Recamier', 'It depicts the renowned Parisian socialite reclining on a Directoire-style daybed, wearing a simple, white Neoclassical empire-line dress with bare feet.', 1800);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (27, 'Women of Algiers in their Apartment', 'The painting depicts a serene yet confined, lavishly decorated, North African, harem interior with three, seated, women in, opulent, textiles, and, gold jewelry, alongside a, fourth, standing, black attendant. The scene captures a, quiet, intimate, mood, with, detailed, textures, of, clothing, and, patterned, carpets, under a, low, soft, light.', 1834);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (28, 'The Death of Sardanapalus', 'It depicts a detached Assyrian king watching his guards slaughter his concubines, slaves, and horses amidst a chaotic, fiery-red bedroom scene. Sardanapalus lies calmly on a massive, crimson-draped bed, looking on with indifference while his world is destroyed.', 1827);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (29, 'The Embarkation for Cythera', 'The painting portrays aristocratic couples in a dreamlike, hazy landscape, likely departing from or arriving at the mythical island of love, Cythera.', 1717);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (30, 'Poires, noix et verre de vin', 'The painting depicts a cup of wine, pears, and some nuts.', 1768);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (31, 'Portrait de Philippe IV, roi d''Espagne, en pied', 'The painting depicts the Spanish king Phillippe IV.', 1624);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (32, 'Portrait of a Seated Woman', 'The painting depicts a woman seated in a chair.', 1653);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (33, 'Apollo Slaying the Serpent Python', 'The painting is a masterpiece of French Romanticism depicting the triumph of light, order, and civilization over darkness and chaos. The dramatic, dynamic scene shows Apollo in a golden chariot, shooting arrows at the monstrous serpent amidst a fiery, colorful sky.', 1850);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (34, 'Dante et Virgile aux Enfers', 'The painting depicts a dramatic, chaotic scene from Canto VIII of Dante Alighieri''s Inferno, showcasing the poets crossing the River Styx into the City of Dis. Dante, clad in a red cloak, and his guide, the classical poet Virgil, are navigating the River Styx in a small, crowded boat rowed by Phlegyas.', 1822);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (35, 'Scene des massacres de Scio', 'It depicts the horrific suffering of civilians during the 1822 massacre on the Greek island of Chios by Ottoman forces. The composition emphasizes dramatic gestures, dynamic movement, and vivid contrasts of light and shadow, hallmarks of the Romantic style.', 1824);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (36, 'Nature morte au homard', 'The painting is a rare, large-scale still life showcasing a dramatic spread of game birds, fish, lobster, and shellfish on a coastal landscape.', 1827);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (37, 'Jeune orpheline au cimetiere', 'It depicts a grief-stricken young girl with tearful eyes, a trembling mouth, and a distressed expression, set against a dark, desolate cemetery background, evoking themes of vulnerability, loss, and despair.', 1824);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (38, 'La Mer vue des hauteurs de Dieppe dit aussi La Mer Dieppe', 'The painting showcases the dramatic and ever-changing nature of the sea as seen from the cliffs above Dieppe. Delacroix uses vivid colors, fluid brushwork, and dynamic composition to convey the movement of waves, the interplay of light on water, and the atmosphere of the coastline.', 1833);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (39, 'Medee furieuse', 'It depicts the mythological figure hiding in a cave, preparing to murder her children to avenge Jason''s betrayal. It showcases intense emotion through powerful, tortured muscularity, chiaroscuro lighting, and a dagger symbolizing imminent violence, highlighting the tragic conflict between maternal love and fury.', 1838);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (40, 'Portrait of Isabella d''Este', 'The portrait of Isabella d''Este features a side-profile view, utilizing black, red, and yellow pastel chalks on paper to capture her features with delicate,intelligent gaze and detailed, elaborate hairstyle.', 1500);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (41, 'Bathsheba at Her Bath', 'It depicts the biblical figure contemplating King Davids summons. The painting uses intense chiaroscuro, highlighting Bathsheba''s pale, luminous skin against a dark, shadowy, and ambiguous background. Rich, warm tones of gold and copper fabrics accentuate her form.', 1654);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (42, 'The Slaughtered Ox', 'It depicts a flayed, decapitated bull carcass hanging in a dark shed. A massive carcass hangs by its hind legs, with its chest cavity opened to reveal raw flesh, fat, and bone. In the dark background, a woman is seen peeking around a doorway, providing scale and a slight narrative, genre-like element.', 1655);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (43, 'L''Archange Raphael quittant la famille de Tobie ou Tobie et sa famille prosternes devant lange', 'This painting depicts the moment from the Book of Tobit (XII) when Tobit, having regained his sight through the intervention of the angel Raphael, gives thanks to God alongside his son Tobie.', 1637);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (44, 'The Death of Marat', 'It depicts the assassinated French revolutionary leader, Jean-Paul Marat, in his bathtub. Marat is shown slumped over in a medicinal bath where he treated a chronic skin condition, turning his workplace into a scene of martyrdom.', 1793);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (45, 'The Lion and The Serpent', 'The sculpture depicts a lion, representing virtue and power, pinning a large, writhing snake to the ground with its right paw. It represents an intense, violent, and highly realistic struggle between a lion and a coiled serpent, symbolizing a confrontation between forces of good and evil. It is a masterpiece of 19th-century French Romanticism that elevated animal sculpture to high art.', 1832);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (46, 'A Lesson in Humility', 'A Lesson in Humility  depicts a famous ancient athlete, Milo, being trapped and devoured by a lion. The sculpture symbolizes the fall of human strength and pride against nature. It represents the height of French Baroque sculpture, characterized by intense emotion, muscular tension, and dramatic motion.', 1671);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (47, 'Le Silence', 'Le Silence is a 18th-century French sculpture, showcasing a young, winged figure with a finger to their lips.', 1755);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (48, 'The Infant Jesus Playing with a Nail', 'The sculpture depicts Jesus as a baby playing with nails and a hammer. The original frame is made of gilded wood and is designed why Gian Lorenzo Bernini.', 1665);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (49, 'Moses', 'The statue despicts Moses sitting with a tablet supporting his right arm.', 1830);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (50, 'Christ on the Cross', 'The piece depicts Crhist on the cross, showing his crucifixion. His hands are spread out and legs pinned together.', 1500);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (51, 'Crown of Louis XV of France', 'The crown is the only surviving crown from the French Ancien Regime. It was created for Louis XV''s coronation.', 1722);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (52, 'The Angouleme Emerald Tiara', 'The tiara features a symmetrical, scrolling foliage design composed of 40 emeralds set in gold and over 1,000 diamonds set in silver.', 1819);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (53, 'The Crown of Empress Eugenie', 'It features eight chased gold eagle arches alternating with palmettes, set with 1,354 diamonds and 56 emeralds.', 1855);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (54, 'Sapphire parure of Queen Marie-Amelie and Queen Hortense', 'The set features natural Ceylon sapphires and diamonds set in gold. Originally belonging to Hortense de Beauharnais, it was purchased by King Louis-Philippe I for Queen Marie-Amelie in 1821.', 1810);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (55, 'Netsuke : enfant assis (karako) sur un tambour perce', 'Small figurine called Netsuke. The child''s head is shaved except for two tufts on the temples. Around the neck hangs a cord with an object he plays with, resembling a door hammer.', 1800);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (56, 'Netsuke : femme et enfant entourant un masque grotesque', 'A seated young woman with black hair sits beside a painted Tengu mask with an exaggerated nose, symbolizing masculinity. A child playfully touches the mask''s nose.', 1800);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (57, 'Netsuke : La courtisane Eguchi no kimi representee en Fugen, le bodhisattva de la Sagesse universelle', 'Netsuke depicts a women sitting on an elephant.', 1800);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (58, 'Scepter of Charles V', 'A ceremonial scepter made for royal use, richly adorned with gold, gemstones, and enamel.', 1380);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (59, 'e Combat du Tessin, de la tenture de lHistoire de Scipion', 'Tapestry depicting the battle of the Ticino. his copy was made at the Gobelins Manufactory for Louis XIV in 1688 by de la Croix pere, after the original tapestry woven in Brussels around 1558 for Marshal de Saint-Andre.', 1688);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (60, 'Le mois de mars ou Le signe du belier ou La chasse au faucon', 'Tapestry', 1531);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (61, 'Le mois de mai ou Le signe des gemeaux ou L''assemblee', 'Tapestry', 1531);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (62, 'Le mois d''octobre ou Le signe du scorpion ou La curee', 'Tapestry', 1531);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (63, 'Le mois d''aout ou Le signe la vierge ou Le limier', 'Tapestry', 1531);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (64, 'Le mois de juin ou Le signe du cancer ou Le Repas de chasse', 'Tapestry', 1531);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (65, 'Le mois de decembre ou signe du capricorne ou La chasse au sanglier', 'Tapestry', 1531);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (66, 'Le mois de janvier ou Le signe du verseau ou La flambee du sanglier', 'Tapestry', 1531);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (67, 'Casque orne d''une tete de loup', 'Headpiece in bronze.', 1685);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (68, 'Vase fuseau de Madame Mere', 'Vase made of ceramic, porcelain, and bronze.', 1810);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (69, 'Casque orne d''une tete de dauphin', 'Headpiece made out of bronze.', 1685);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (70, 'Bouclier retourne', 'Shild made out of bronze.', 1685);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (71, 'Pertuisane', 'Pole weapon made out of bronze.', 1685);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (72, 'Bouclier aux lions', 'Shield made out of bronze with lion head.', 1685);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (73, 'Casque orne d''un masque de feuillage', 'Headpiece made out of bronze with wolf head.', 1685);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (74, 'Bouclier orne d''un foudre', 'Shild made out of bronze with sword on the front.', 1685);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (75, 'Hallebarde', 'Spear made out of bronze.', 1685);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (76, 'Manteau de chevalier de l''Ordre du Saint-Esprit au chiffre L', 'A ceremonial costume piece made of black silk velvet. It is decorated with gold embroidery depicting flames.', 1722);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (77, 'Manteau d''officier de l''Ordre du Saint-Esprit', 'A ceremonial mantle made of black silk velvet, richly embroidered with gold patterns.', 1722);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (78, 'Netsuke : Onna-san-no-miya', 'Netsuke figurine of a woman and a dog.', 1800);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (79, 'Manju netsuke avec une femme frappant sa table de cuisine', 'Traditional Japanese toggle depicting a woman hitting a table.', 1800);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (80, 'L''Esclave mourant, copie d''apres la sculpture de Michel-Ange', 'A sketch of Michelangelo''s Dying Slave sculpture. It with a black crayon and on paper.', 1855);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (81, 'La sortie du bain', 'It depicts a female figure in intimate, post-bath moments. Degas uses pastels to focus on the natural, often awkward, motions of the body, highlighting anatomical, candid poses from a voyeuristic perspective.', 1895);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (82, 'Ni apparence ni illusion. "Le mur est la surface de sa propre histoire enfouie. Tant que les objets restent dessus, le spectateur cache la vue a l''archologue."', 'The work focuses on the physicality and history of the wall itself, emphasizing the interaction between objects, space, and perception.', 2005);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (83, 'Ni apparence ni illusion. "Quinze pierres en place, toutes sorties de l''ombre, ces mots lumineux rendent visibles a la fois celui qui voit et celui qui est vu. Le mur, le passage."', 'The piece reflects on hidden layers, memory, and the passage of time, rather than creating a traditional image or narrative.', 2005);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (84, 'Ni apparence ni illusion. "detail se dilate."', 'The work focuses on the physicality and history of the wall itself, emphasizing the interaction between objects, space, and perception.', 2005);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (85, 'Round watch', 'A roudn watch with Venus depicted on the front.', 1760);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (86, 'Round watch', 'A round watch with flowers on the front.', 1757);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (87, 'Pianino', 'Piano made out of bronze with gold accents.', 1835);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (88, 'Crown of Charlemagne', 'Crown gilded with silver with 40 cameos and intaglios. It was made for crown made for Napoleon I.', 1804);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (89, 'Coffin of the Lady Madja', 'An anthropoid wooden coffin from Deir el-Medina', 1479);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (90, 'Portrait du peintre Jacques Louis David', 'Portrait of the famous painter Jacques Louis David.', 1825);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (91, 'Portrait de Marie Amelie Josephine, archiduchesse d''Autriche, infante, duchesse de Parme', NULL, 1700);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (92, 'Portrait d''homme', NULL, 1658);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (93, 'Portrait de Louis-Philippe Ier, roi des Francais', 'Half body portrait of King Louis-Phillippe.', 1844);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (94, 'Portrait de Claude Louis Lecomte', NULL, 1790);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (95, 'Konstantin Kanaris', 'Coin depiccting Konstantin Kanaris. It is made out of bronze.', 1852);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (96, 'Germain Pilon', 'Coin depiccting Germain Pilon. It is made out of bronze.', 1856);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (97, 'Despoina Kanaris', 'Coin depiccting Despiona Kanaris. It is made out of bronze.', 1852);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (98, 'Ebih-Il, of Mari', 'The statue is a masterpiece of Early Dynastic Sumerian art. It was discovered in the Temple of Ishtar at Mari, Syria. The figure is seated on a woven wicker cushion, with his torso bare and a serene, smiling expression.', -2400);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (99, 'The Seated Scribe', 'The sculpture is a famous work of ancient Egyptian art. It represents a figure of a seated scribe at work.', -2500);
INSERT INTO Artifacts (artifact_id, name, description, date_of_creation) VALUES (100, 'The Great Sphinx of Tanis', 'The sculpture is a colossal, 24-ton statue representing a human-headed lion. It depicts a recumbent lion with a human face and a shen hieroglyph on the base, symbolizing royal power.', -2600);

-- Exhibitions
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (1, 'Ancient civilizations', 'Sculptures and artifacts from ancient Egypt and Mesopotamia highlighting early artistic traditions', '2025-01-10', '2026-05-10');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (2, 'Renaissance masters', 'Works from the Renaissance including paintings and sculptures by Leonardo da Vinci and Michelangelo', '2025-01-25', '2026-10-05');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (3, 'Portraits', 'Portraits of kings, queens, nobles.', '2024-02-10', '2024-12-01');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (4, 'Arms and armor', 'Historic armor, shields, and ceremonial weapons illustrating craftsmanship and warfare.', '2024-05-01', '2025-06-20');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (5, 'Japanese art', 'Netsukes from the Edo-period in Japan.', '2024-02-01', '2025-11-26');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (6, 'Textiles and tapestry', 'Historic tapestries and textile artworks depicting mythology, seasons, court life, etc.', '2025-02-12', '2025-11-03');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (7, 'The age of romaticism', 'Romantic artworks exploring emotion, revolution, and dramatic storytelling', '2025-06-01', '2026-04-28');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (8, 'exhibition01', 'A curated selection of all kinds of works.', '2024-10-05', '2026-02-17');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (9, 'exhibition02', 'Special thematic exhibition exploring cultural heritage and artistic traditions from around the world.', '2025-03-31', '2026-07-28');
INSERT INTO Exhibitions (exhibition_id, name, description, start_date, end_date) VALUES (10, 'exhibition03', 'Highlights from the museums permanent collection, featuring paintings, sculptures, and artifacts.', '2024-01-30', '2024-12-30');

-- Paintings
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (11, 'Wood panel', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (12, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (13, 'Wood panel', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (14, 'Walnut wood', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (15, 'Wood panel', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (16, 'Wall', 'Fresco');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (17, 'Wood panel', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (18, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (19, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (20, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (21, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (22, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (23, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (24, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (25, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (26, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (27, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (28, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (29, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (30, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (31, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (32, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (33, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (34, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (35, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (36, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (37, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (38, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (39, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (40, 'Paper', 'Chalk');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (41, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (42, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (43, 'Canvas', 'Oil');
INSERT INTO Paintings (artifact_id, medium, paint_type) VALUES (44, 'Canvas', 'Oil');

-- Sculpture
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (1, 'Parian marble', 'Height: 5.57m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (2, 'Marble', 'Height: 2.29m, Width: 0.74m, Depth: 0.58m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (3, 'Marble', 'Height: 2.15m, Width: 0.55m, Depth: 0.75m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (4, 'Marble', 'Height: 1.55m, Width: 1.68m, Depth: 1.01m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (5, 'Parian marble', 'Height: 2.04m, Width: 0.67m, Depth: 0.61m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (6, 'Marble', 'Height: 1.69m, Wdith: 0.89m, Depth: 0.89m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (7, 'Parian marble', 'Height: 1.99m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (8, 'Carrara marble', 'Height: 3.15m, Width: 2.91m, Depth: 1.28m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (9, 'Carrara marble', 'Height: 3.40m, Width: 2.84m, Depth: 1.27m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (10, 'Marble', 'Height: 3.12m, Width: 1.28m, Depth: 0.64m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (45, 'Bronze', 'Height: 1.35m, Width: 1.78m, Depth: 0.06m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (46, 'Carrara marble', 'Height: 3.32m, Width: 2.96m, Depth: 0.44m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (47, 'Bronze', 'Height: 0.72m, Width: 0.27m, Depth: 0.22m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (48, 'Marble', 'Height: 0.63m, Wdith: 0.80m, Depth: 0.17m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (49, 'Terracotta', 'Height: 0.50m, Width: 0.21m, Depth: 0.21');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (50, 'Polychrome linden wood', 'Height: 0.447?m, Width: 0.42?m, Depth: 0.09m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (99, 'Painted limestone', 'Height: 0.53m, Width: 0.44m, Depth: 0.35m');
INSERT INTO Sculpture (artifact_id, material, dimensions) VALUES (100, 'Granite', 'Height: 1.83m, Width: 1.53m, Depth: 4.80m');

-- Photographs
INSERT INTO Photographs (artifact_id, film_type) VALUES (90, 'Colour');
INSERT INTO Photographs (artifact_id, film_type) VALUES (91, 'Colour');
INSERT INTO Photographs (artifact_id, film_type) VALUES (92, 'Colour');
INSERT INTO Photographs (artifact_id, film_type) VALUES (93, 'Colour');
INSERT INTO Photographs (artifact_id, film_type) VALUES (94, 'Colour');

-- Tours
INSERT INTO Tours (tour_id, description, cost, employee_id) VALUES (1, 'Highlights of the Louvre including famous masterpieces.', 15.0, 1);
INSERT INTO Tours (tour_id, description, cost, employee_id) VALUES (2, 'Romanticism and revolutionary art tour.', 20.0, 4);
INSERT INTO Tours (tour_id, description, cost, employee_id) VALUES (3, 'Decorative arts and royal treasures tour.', 17.0, 2);
INSERT INTO Tours (tour_id, description, cost, employee_id) VALUES (4, 'Tour explores ancient Egyptian and Mesopotamian artifacts.', 12.0, 3);
INSERT INTO Tours (tour_id, description, cost, employee_id) VALUES (5, 'Renaissance art tour featuring Leonardo da Vinci and Michelangelo.', 7.5, 1);

-- TourDates
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (1, '2025-07-05', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (1, '2025-07-05', '14:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (1, '2025-08-10', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (1, '2025-08-10', '12:30:00', '14:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (1, '2025-08-10', '15:00:00', '17:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (1, '2026-02-05', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (1, '2026-01-20', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (1, '2026-03-02', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-07-10', '10:00:00', '14:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-08-10', '10:00:00', '14:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-09-10', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-10-10', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-11-10', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-12-10', '10:00:00', '14:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2026-01-10', '10:00:00', '14:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-07-20', '10:00:00', '14:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-08-20', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-09-20', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-10-20', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-11-05', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2025-10-05', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2026-01-05', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (2, '2026-01-30', '12:00:00', '16:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (3, '2024-05-06', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (3, '2024-06-10', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (3, '2024-07-27', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (3, '2024-11-29', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (3, '2024-09-27', '10:00:00', '12:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (4, '2026-04-15', '10:00:00', '11:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (4, '2026-04-15', '12:00:00', '13:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (4, '2026-04-15', '14:00:00', '15:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (4, '2026-04-20', '10:00:00', '11:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (4, '2026-04-20', '12:00:00', '13:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (4, '2026-04-20', '14:00:00', '15:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (4, '2025-12-03', '10:00:00', '11:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (4, '2025-12-02', '12:00:00', '13:30:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-15', '14:00:00', '15:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-15', '12:00:00', '13:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-15', '10:00:00', '11:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-20', '14:00:00', '15:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-20', '12:00:00', '13:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-20', '10:00:00', '11:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-10', '14:00:00', '15:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-10', '12:00:00', '13:00:00');
INSERT INTO TourDates (tour_id, date, start_time, end_time) VALUES (5, '2026-04-10', '10:00:00', '11:00:00');

-- Displays
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (98, 1, 'A01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (99, 1, 'A01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (100, 1, 'A01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (89, 1, 'A01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (40, 2, 'B04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (80, 2, 'B04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (2, 2, 'B04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (3, 2, 'B04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (11, 2, 'B04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (12, 2, 'B04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (13, 2, 'B04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (16, 2, 'B04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (15, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (26, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (31, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (32, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (90, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (91, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (92, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (93, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (94, 3, 'B02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (69, 4, 'C10');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (70, 4, 'C10');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (71, 4, 'C10');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (72, 4, 'C10');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (73, 4, 'C10');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (74, 4, 'C10');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (75, 4, 'C10');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (78, 5, 'C07');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (79, 5, 'C07');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (55, 5, 'C07');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (56, 5, 'C07');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (57, 5, 'C07');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (58, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (59, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (60, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (61, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (62, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (63, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (64, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (65, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (66, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (68, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (76, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (77, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (87, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (95, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (96, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (97, 6, 'A04');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (12, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (20, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (27, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (28, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (33, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (34, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (35, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (36, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (37, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (38, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (39, 7, 'B01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (29, 8, 'A02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (41, 8, 'A02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (45, 8, 'A02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (7, 8, 'A02');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (19, 9, 'A08');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (21, 9, 'A08');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (1, 10, 'D01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (4, 10, 'D01');
INSERT INTO Displays (artifact_id, exhibition_id, room) VALUES (5, 10, 'D01');

-- Creates
INSERT INTO Creates (artifact_id, artist_id) VALUES (1, 1);
INSERT INTO Creates (artifact_id, artist_id) VALUES (2, 2);
INSERT INTO Creates (artifact_id, artist_id) VALUES (3, 2);
INSERT INTO Creates (artifact_id, artist_id) VALUES (4, 3);
INSERT INTO Creates (artifact_id, artist_id) VALUES (5, 4);
INSERT INTO Creates (artifact_id, artist_id) VALUES (6, 5);
INSERT INTO Creates (artifact_id, artist_id) VALUES (7, 6);
INSERT INTO Creates (artifact_id, artist_id) VALUES (8, 7);
INSERT INTO Creates (artifact_id, artist_id) VALUES (9, 8);
INSERT INTO Creates (artifact_id, artist_id) VALUES (10, 8);
INSERT INTO Creates (artifact_id, artist_id) VALUES (11, 9);
INSERT INTO Creates (artifact_id, artist_id) VALUES (12, 10);
INSERT INTO Creates (artifact_id, artist_id) VALUES (13, 9);
INSERT INTO Creates (artifact_id, artist_id) VALUES (14, 9);
INSERT INTO Creates (artifact_id, artist_id) VALUES (15, 9);
INSERT INTO Creates (artifact_id, artist_id) VALUES (16, 11);
INSERT INTO Creates (artifact_id, artist_id) VALUES (17, 12);
INSERT INTO Creates (artifact_id, artist_id) VALUES (18, 13);
INSERT INTO Creates (artifact_id, artist_id) VALUES (19, 14);
INSERT INTO Creates (artifact_id, artist_id) VALUES (20, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (21, 12);
INSERT INTO Creates (artifact_id, artist_id) VALUES (22, 16);
INSERT INTO Creates (artifact_id, artist_id) VALUES (23, 16);
INSERT INTO Creates (artifact_id, artist_id) VALUES (24, 17);
INSERT INTO Creates (artifact_id, artist_id) VALUES (25, 16);
INSERT INTO Creates (artifact_id, artist_id) VALUES (26, 16);
INSERT INTO Creates (artifact_id, artist_id) VALUES (27, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (28, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (29, 18);
INSERT INTO Creates (artifact_id, artist_id) VALUES (30, 19);
INSERT INTO Creates (artifact_id, artist_id) VALUES (31, 20);
INSERT INTO Creates (artifact_id, artist_id) VALUES (32, 21);
INSERT INTO Creates (artifact_id, artist_id) VALUES (33, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (34, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (35, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (36, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (37, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (38, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (39, 15);
INSERT INTO Creates (artifact_id, artist_id) VALUES (40, 9);
INSERT INTO Creates (artifact_id, artist_id) VALUES (41, 22);
INSERT INTO Creates (artifact_id, artist_id) VALUES (42, 22);
INSERT INTO Creates (artifact_id, artist_id) VALUES (43, 22);
INSERT INTO Creates (artifact_id, artist_id) VALUES (44, 16);
INSERT INTO Creates (artifact_id, artist_id) VALUES (45, 23);
INSERT INTO Creates (artifact_id, artist_id) VALUES (46, 24);
INSERT INTO Creates (artifact_id, artist_id) VALUES (47, 25);
INSERT INTO Creates (artifact_id, artist_id) VALUES (48, 5);
INSERT INTO Creates (artifact_id, artist_id) VALUES (49, 2);
INSERT INTO Creates (artifact_id, artist_id) VALUES (50, 2);
INSERT INTO Creates (artifact_id, artist_id) VALUES (51, 26);
INSERT INTO Creates (artifact_id, artist_id) VALUES (52, 27);
INSERT INTO Creates (artifact_id, artist_id) VALUES (52, 28);
INSERT INTO Creates (artifact_id, artist_id) VALUES (53, 29);
INSERT INTO Creates (artifact_id, artist_id) VALUES (54, 1);
INSERT INTO Creates (artifact_id, artist_id) VALUES (55, 30);
INSERT INTO Creates (artifact_id, artist_id) VALUES (56, 31);
INSERT INTO Creates (artifact_id, artist_id) VALUES (57, 31);
INSERT INTO Creates (artifact_id, artist_id) VALUES (58, 32);
INSERT INTO Creates (artifact_id, artist_id) VALUES (59, 33);
INSERT INTO Creates (artifact_id, artist_id) VALUES (60, 34);
INSERT INTO Creates (artifact_id, artist_id) VALUES (61, 34);
INSERT INTO Creates (artifact_id, artist_id) VALUES (62, 34);
INSERT INTO Creates (artifact_id, artist_id) VALUES (63, 34);
INSERT INTO Creates (artifact_id, artist_id) VALUES (64, 34);
INSERT INTO Creates (artifact_id, artist_id) VALUES (65, 34);
INSERT INTO Creates (artifact_id, artist_id) VALUES (66, 34);
INSERT INTO Creates (artifact_id, artist_id) VALUES (67, 35);
INSERT INTO Creates (artifact_id, artist_id) VALUES (68, 16);
INSERT INTO Creates (artifact_id, artist_id) VALUES (69, 35);
INSERT INTO Creates (artifact_id, artist_id) VALUES (70, 35);
INSERT INTO Creates (artifact_id, artist_id) VALUES (71, 35);
INSERT INTO Creates (artifact_id, artist_id) VALUES (72, 35);
INSERT INTO Creates (artifact_id, artist_id) VALUES (73, 35);
INSERT INTO Creates (artifact_id, artist_id) VALUES (74, 35);
INSERT INTO Creates (artifact_id, artist_id) VALUES (75, 35);
INSERT INTO Creates (artifact_id, artist_id) VALUES (76, 1);
INSERT INTO Creates (artifact_id, artist_id) VALUES (77, 1);
INSERT INTO Creates (artifact_id, artist_id) VALUES (78, 36);
INSERT INTO Creates (artifact_id, artist_id) VALUES (79, 37);
INSERT INTO Creates (artifact_id, artist_id) VALUES (80, 38);
INSERT INTO Creates (artifact_id, artist_id) VALUES (81, 38);
INSERT INTO Creates (artifact_id, artist_id) VALUES (82, 39);
INSERT INTO Creates (artifact_id, artist_id) VALUES (83, 39);
INSERT INTO Creates (artifact_id, artist_id) VALUES (84, 39);
INSERT INTO Creates (artifact_id, artist_id) VALUES (85, 42);
INSERT INTO Creates (artifact_id, artist_id) VALUES (85, 41);
INSERT INTO Creates (artifact_id, artist_id) VALUES (85, 40);
INSERT INTO Creates (artifact_id, artist_id) VALUES (86, 40);
INSERT INTO Creates (artifact_id, artist_id) VALUES (87, 44);
INSERT INTO Creates (artifact_id, artist_id) VALUES (87, 43);
INSERT INTO Creates (artifact_id, artist_id) VALUES (88, 32);
INSERT INTO Creates (artifact_id, artist_id) VALUES (89, 1);
INSERT INTO Creates (artifact_id, artist_id) VALUES (90, 45);
INSERT INTO Creates (artifact_id, artist_id) VALUES (91, 46);
INSERT INTO Creates (artifact_id, artist_id) VALUES (92, 47);
INSERT INTO Creates (artifact_id, artist_id) VALUES (93, 48);
INSERT INTO Creates (artifact_id, artist_id) VALUES (93, 49);
INSERT INTO Creates (artifact_id, artist_id) VALUES (94, 32);
INSERT INTO Creates (artifact_id, artist_id) VALUES (95, 50);
INSERT INTO Creates (artifact_id, artist_id) VALUES (96, 50);
INSERT INTO Creates (artifact_id, artist_id) VALUES (97, 50);
INSERT INTO Creates (artifact_id, artist_id) VALUES (98, 1);
INSERT INTO Creates (artifact_id, artist_id) VALUES (99, 1);
INSERT INTO Creates (artifact_id, artist_id) VALUES (100, 1);

-- Exhibition_Genre
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (1, 'Egyptian');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (1, 'Summerian');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (2, 'Renaissance');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (3, 'Renaissance');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (3, 'Neoclassic');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (3, 'Baroque');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (3, 'Romanticism');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (4, 'Armory');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (5, 'Japanese Edo-period');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (6, 'Gothic');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (6, 'Baroque');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (6, 'Renaissance');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (6, 'Clothing');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (6, 'Decorative art');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (6, 'Coins and medals');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (7, 'Romanticism');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (8, 'Rococo');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (8, 'Baroque');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (8, 'Romanticism');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (8, 'Hellenistic');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (8, 'Realism');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (9, 'Mannerism');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (9, 'Baroque');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (10, 'Hellenistic');
INSERT INTO Exhibition_Genre (exhibition_id, genre_name) VALUES (10, 'Neoclassic');

-- Artifact_Genre
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (1, 'Hellenistic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (2, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (3, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (4, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (5, 'Hellenistic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (6, 'Hellenistic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (7, 'Hellenistic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (8, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (9, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (9, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (10, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (10, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (11, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (12, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (13, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (14, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (15, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (16, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (17, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (18, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (18, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (19, 'Mannerism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (20, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (21, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (22, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (23, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (24, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (25, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (26, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (27, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (28, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (29, 'Rococo');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (30, 'Rococo');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (31, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (32, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (33, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (34, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (35, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (36, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (37, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (38, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (39, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (40, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (41, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (42, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (43, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (44, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (45, 'Realism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (45, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (46, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (47, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (48, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (49, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (50, 'Religious');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (51, 'Rococo');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (51, 'Jewels');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (52, 'Jewels');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (53, 'Jewels');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (54, 'Jewels');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (55, 'Japanese Edo-period');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (56, 'Japanese Edo-period');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (57, 'Japanese Edo-period');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (58, 'Gothic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (59, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (60, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (61, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (62, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (63, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (64, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (65, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (66, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (67, 'Armory');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (68, 'Decorative art');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (69, 'Armory');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (70, 'Armory');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (71, 'Armory');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (72, 'Armory');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (73, 'Armory');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (74, 'Armory');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (75, 'Armory');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (76, 'Clothing');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (77, 'Clothing');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (78, 'Japanese Edo-period');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (79, 'Japanese Edo-period');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (80, 'Renaissance');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (81, 'Impressionism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (82, 'Contemporary');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (83, 'Contemporary');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (84, 'Contemporary');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (85, 'Rococo');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (86, 'Rococo');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (87, 'Decorative art');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (88, 'Jewels');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (89, 'Egyptian');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (90, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (91, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (92, 'Baroque');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (93, 'Romanticism');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (94, 'Neoclassic');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (95, 'Coins and medals');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (96, 'Coins and medals');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (97, 'Coins and medals');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (98, 'Sumerian');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (99, 'Egyptian');
INSERT INTO Artifact_Genre (artifact_id, genre_name) VALUES (100, 'Egyptian');

-- Tour_Exhibitions
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (2, 1);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (7, 1);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (1, 2);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (2, 2);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (7, 2);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (8, 2);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (9, 2);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (4, 3);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (5, 3);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (3, 3);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (10, 3);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (1, 4);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (2, 4);
INSERT INTO Tour_Exhibitions (exhibition_id, tour_id) VALUES (9, 5);

-- Organizer 
INSERT INTO Organizer (employee_id, tour_id) VALUES (10, 1);
INSERT INTO Organizer (employee_id, tour_id) VALUES (2, 1);
INSERT INTO Organizer (employee_id, tour_id) VALUES (5, 2);
INSERT INTO Organizer (employee_id, tour_id) VALUES (4, 2);
INSERT INTO Organizer (employee_id, tour_id) VALUES (9, 2);
INSERT INTO Organizer (employee_id, tour_id) VALUES (2, 2);
INSERT INTO Organizer (employee_id, tour_id) VALUES (4, 3);
INSERT INTO Organizer (employee_id, tour_id) VALUES (7, 3);
INSERT INTO Organizer (employee_id, tour_id) VALUES (7, 4);
INSERT INTO Organizer (employee_id, tour_id) VALUES (8, 5);

-- Reservation 
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('cnani0@studiopress.com', 1, '2025-07-05', '10:00:00', '2025-05-30');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('afrays1@elegantthemes.com', 2, '2026-01-30', '12:00:00', '2025-12-27');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('nathan222@shinystat.com', 3, '2024-07-27', '10:00:00', '2024-06-23');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('mdurdan3@bigcartel.com', 4, '2026-04-15', '12:00:00', '2025-12-29');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('rclulee4@alibaba.com', 4, '2026-04-15', '12:00:00', '2026-04-01');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('natwood4@cnet.com', 4, '2026-04-15', '12:00:00', '2026-03-15');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('zach4000@yahoo.com', 2, '2026-01-30', '12:00:00', '2026-01-05');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('slaviste9@nhs.uk', 2, '2026-01-30', '12:00:00', '2026-01-20');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('cguppya@google.nl', 2, '2025-12-10', '10:00:00', '2025-10-13');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('lrumbleb@weebly.com', 1, '2025-08-10', '15:00:00', '2025-06-20');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('ewhichelowc@biglobe.ne.jp', 3, '2024-06-10', '10:00:00', '2024-03-01');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('cioselevichd@networksolutions.com', 2, '2026-01-30', '12:00:00', '2026-01-02');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('ggainforthe@ox.ac.uk', 5, '2026-04-15', '10:00:00', '2026-02-02');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('mrelf2@newsvine.com', 4, '2026-04-20', '14:00:00', '2025-11-30');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('abroosea@chronoengine.com', 4, '2026-04-15', '12:00:00', '2025-12-20');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('sdunsb@quantcast.com', 4, '2026-04-20', '14:00:00', '2026-01-30');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('lgraystonc@gravatar.com', 4, '2026-04-20', '14:00:00', '2026-03-30');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('sferrullid@sogou.com', 4, '2025-12-03', '10:00:00', '2025-11-03');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('jsaintepaule@privacy.gov.au', 1, '2025-08-10', '12:30:00', '2025-07-01');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('abroosea@chronoengine.com', 5, '2026-04-10', '14:00:00', '2026-02-18');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('lgraystonc@gravatar.com', 1, '2026-02-05', '10:00:00', '2026-01-23');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('jsaintepaule@privacy.gov.au', 5, '2026-04-15', '14:00:00', '2026-04-05');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('mmorais0@nationalgeographic.com', 4, '2026-04-15', '12:00:00', '2026-01-04');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('mmorais0@nationalgeographic.com', 5, '2026-04-15', '10:00:00', '2026-01-04');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('mmorais0@nationalgeographic.com', 2, '2025-07-20', '10:00:00', '2025-03-20');
INSERT INTO Reservation (email, tour_id, date, start_time, booking_date) VALUES ('mmorais0@nationalgeographic.com', 3, '2024-11-29', '10:00:00', '2024-09-30');








